services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - '80:80'
        env_file:
            - .env
        volumes:
            - 'sqlite-data:/var/www/html/database'
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    sqlite-data:
        driver: local
